v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
P 4 1 1500 -790 {}
T {Based on a template made by R. Timothy Edwards
November 27, 2023
Revision 0
Open sourced under Apache 2.0 license} 1930 -1640 0 0 0.4 0.4 {}
N 690 -610 810 -610 {
lab=VSUB}
N 1780 -970 1960 -970 {
lab=VSUB}
N 920 -940 1500 -940 {
lab=#net1}
N 810 -610 1420 -610 {
lab=VSUB}
N 690 -1160 1540 -1160 {
lab=vdd}
N 1140 -900 1140 -670 {
lab=vss}
N 1140 -900 1540 -900 {
lab=vss}
N 920 -940 920 -670 {
lab=#net1}
N 690 -1160 690 -770 {
lab=vdd}
N 690 -710 690 -610 {
lab=VSUB}
N 810 -1060 810 -770 {
lab=inp}
N 810 -710 810 -610 {
lab=VSUB}
N 670 -610 690 -610 {
lab=VSUB}
N 1540 -990 1540 -900 {lab=vss}
N 1500 -970 1500 -940 {lab=#net1}
N 1420 -1000 1450 -1000 {lab=inm}
N 1420 -1000 1420 -840 {lab=inm}
N 1630 -1030 1980 -1030 {lab=out}
N 1540 -1160 1540 -1070 {lab=vdd}
N 1420 -840 1480 -840 {lab=inm}
N 1420 -750 1420 -610 {
lab=VSUB}
N 1420 -840 1420 -810 {lab=inm}
N 1540 -840 1630 -840 {lab=out}
N 1630 -1030 1630 -840 {lab=out}
N 1620 -1030 1630 -1030 {lab=out}
N 1390 -1000 1420 -1000 {lab=inm}
N 810 -1060 1450 -1060 {lab=inp}
N 1540 -900 1710 -900 {lab=vss}
N 1710 -1310 1710 -900 {lab=vss}
N 1580 -1320 1620 -1320 {lab=inp}
N 1580 -1350 1580 -1320 {lab=inp}
N 1580 -1380 1620 -1380 {lab=inp}
N 800 -1060 810 -1060 {lab=inp}
N 810 -1350 810 -1060 {lab=inp}
N 810 -1350 1580 -1350 {lab=inp}
N 1580 -1380 1580 -1350 {lab=inp}
N 1540 -1430 1540 -1160 {lab=vdd}
N 1540 -1430 1710 -1430 {lab=vdd}
N 1710 -1430 1710 -1390 {lab=vdd}
N 1920 -1290 2020 -1290 {
lab=VSUB}
N 1790 -1350 2040 -1350 {lab=out1}
N 1670 -1290 1670 -1250 {lab=#net2}
N 1670 -1190 1670 -1170 {lab=VSUB}
N 1670 -1170 1920 -1170 {lab=VSUB}
N 1920 -1290 1920 -1170 {lab=VSUB}
N 1840 -1290 1920 -1290 {
lab=VSUB}
C {OTA1336.sym} 1530 -1030 0 0 {name=x1}
C {devices/code_shown.sym} 30 -1690 0 0 {
name=SETUP only_toplevel=false value="* CACE gensim simulation file CACE\{filename\}_CACE\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include CACE\{DUT_path\}

.lib cornerMOSlv.lib CACE\{corner\}
.lib cornerCAP.lib cap_typ
.lib cornerRES.lib res_typ

.option TEMP=CACE\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {isource.sym} 920 -640 0 0 {name=Ibias value="DC CACE\{Ibias\}"}
C {title-3.sym} 0 0 0 0 {name=l2 author="IHP-GmbH 2026" title="CACE CMRR template" rev=1.0 lock=true}
C {devices/code_shown.sym} 20 -1400 0 0 {name=CONTROL1 only_toplevel=false value=".control
ac dec 1001 10 100meg 
let CMRR = db((v(out)/v(inp))/(v(out1)/v(inp)))
meas ac cmrrdb max CMRR
echo $&cmrrdb > CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data
quit
.endc
"}
C {devices/lab_pin.sym} 670 -610 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 1140 -640 0 0 {name=Vvss value="DC CACE\{Vvss\}" savecurrent=false}
C {devices/lab_wire.sym} 1290 -1160 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} 1290 -900 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} 1980 -1030 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/res.sym} 1780 -1000 0 0 {name=Rout
value=CACE\{Rout\}
device=resistor}
C {devices/capa.sym} 1920 -1000 0 0 {name=Cout
value=CACE\{Cout\}}
C {devices/lab_pin.sym} 1960 -970 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 690 -740 0 0 {name=Vvdd value="DC CACE\{Vvdd\}" savecurrent=false}
C {devices/res.sym} 990 -580 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 990 -550 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} 800 -1060 0 0 {name=p2 sig_type=std_logic lab=inp}
C {devices/lab_pin.sym} 1390 -1000 0 0 {name=p4 sig_type=std_logic lab=inm}
C {ind.sym} 1510 -840 1 0 {name=L6
m=1
value=4G
footprint=1206
device=inductor}
C {capa.sym} 1420 -780 0 0 {name=C1
m=1
value=4G
footprint=1206
device="ceramic capacitor"}
C {vsource.sym} 810 -740 0 0 {name=V1 value="DC CACE\{Vcm\} AC 1 0"
}
C {OTA1336.sym} 1700 -1350 0 0 {name=x2}
C {devices/lab_wire.sym} 2040 -1350 0 0 {name=p3 sig_type=std_logic lab=out1}
C {devices/res.sym} 1840 -1320 0 0 {name=Rout1
value=CACE\{Rout\}
device=resistor}
C {devices/capa.sym} 1980 -1320 0 0 {name=Cout1
value=CACE\{Cout\}}
C {devices/lab_pin.sym} 2020 -1290 0 1 {name=p5 sig_type=std_logic lab=VSUB}
C {isource.sym} 1670 -1220 0 0 {name=Ibias1 value="DC CACE\{Ibias\}"}
