v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
T {Based on a template made by R. Timothy Edwards
November 27, 2023
Revision 0
Open sourced under Apache 2.0 license} 2000 -1720 0 0 0.4 0.4 {}
N 680 -810 1150 -810 {
lab=VSUB}
N 1790 -1170 1970 -1170 {
lab=VSUB}
N 930 -1140 1550 -1140 {
lab=#net1}
N 820 -1270 1460 -1270 {
lab=inp}
N 700 -1360 700 -870 {
lab=vdd}
N 700 -1360 1590 -1360 {
lab=vdd}
N 1150 -1100 1150 -870 {
lab=vss}
N 1150 -1100 1590 -1100 {
lab=vss}
N 930 -1140 930 -870 {
lab=#net1}
N 820 -1190 820 -870 {
lab=inm}
N 820 -1190 1460 -1190 {
lab=inm}
N 820 -1270 820 -1250 {
lab=inp}
N 1590 -1360 1590 -1270 {lab=vdd}
N 1590 -1190 1590 -1100 {lab=vss}
N 1550 -1170 1550 -1140 {lab=#net1}
N 1460 -1200 1460 -1190 {lab=inm}
N 1460 -1200 1500 -1200 {lab=inm}
N 1460 -1260 1500 -1260 {lab=inp}
N 1460 -1270 1460 -1260 {lab=inp}
N 1670 -1230 1990 -1230 {lab=out}
C {devices/vsource.sym} 820 -840 0 0 {name=VVcm value="DC CACE\{Vcm\}" savecurrent=false}
C {devices/lab_pin.sym} 680 -810 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 1150 -840 0 0 {name=Vvss value="DC CACE\{Vvss\}" savecurrent=false}
C {devices/lab_wire.sym} 1300 -1360 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} 1300 -1100 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} 1990 -1230 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/res.sym} 1790 -1200 0 0 {name=Rout
value=CACE\{Rout\}
device=resistor}
C {devices/capa.sym} 1930 -1200 0 0 {name=Cout
value=CACE\{Cout\}}
C {devices/lab_pin.sym} 1970 -1170 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 700 -840 0 0 {name=Vvdd value="DC CACE\{Vvdd\}" savecurrent=false}
C {devices/code_shown.sym} 50 -1350 0 0 {name=CONTROL only_toplevel=false value=".control
op
set wr_singlescale
wrdata CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data -I(Vvdd)
quit
.endc
"}
C {devices/code_shown.sym} 40 -1660 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file CACE\{filename\}_CACE\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include CACE\{DUT_path\}

.lib cornerMOSlv.lib CACE\{corner\}
.lib cornerCAP.lib cap_typ
.lib cornerRES.lib res_typ

.option TEMP=CACE\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/res.sym} 1000 -780 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 1000 -750 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} 820 -1270 0 0 {name=p2 sig_type=std_logic lab=inp}
C {devices/vsource.sym} 820 -1220 0 0 {name=VVdiff value="DC CACE\{Vdiff\}" savecurrent=false}
C {devices/lab_pin.sym} 820 -1130 0 0 {name=p3 sig_type=std_logic lab=inm}
C {OTA1336.sym} 1580 -1230 0 0 {name=x1}
C {isource.sym} 930 -840 0 0 {name=Ibias value="DC CACE\{Ibias\}"}
C {title-3.sym} 0 0 0 0 {name=l2 author="IHP-GmbH 2026" title="CACE template DC Current VDD" rev=1.0 lock=true}
