v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
T {Based on a template made by R. Timothy Edwards
November 27, 2023
Revision 0
Open sourced under Apache 2.0 license} 1930 -1640 0 0 0.4 0.4 {}
N 790 -590 930 -590 {
lab=VSUB}
N 1830 -1010 2100 -1010 {
lab=out}
N 1900 -950 2080 -950 {
lab=VSUB}
N 930 -590 1790 -590 {
lab=VSUB}
N 930 -1050 1510 -1050 {
lab=inp}
N 810 -1140 810 -650 {
lab=vdd}
N 810 -1140 1630 -1140 {
lab=vdd}
N 1260 -880 1260 -650 {
lab=vss}
N 1260 -880 1630 -880 {
lab=vss}
N 1040 -920 1040 -650 {
lab=#net1}
N 1380 -970 1510 -970 {
lab=inn}
N 1830 -1010 1830 -770 {
lab=out}
N 1790 -590 1830 -590 {
lab=VSUB}
N 1830 -730 1830 -590 {
lab=VSUB}
N 1790 -720 1790 -590 {
lab=VSUB}
N 1380 -780 1790 -780 {
lab=inn}
N 1380 -970 1380 -780 {
lab=inn}
N 930 -1050 930 -780 {
lab=inp}
N 930 -720 930 -590 {
lab=VSUB}
N 1630 -1140 1630 -1050 {lab=vdd}
N 1510 -1040 1540 -1040 {lab=inp}
N 1510 -1050 1510 -1040 {lab=inp}
N 1510 -980 1540 -980 {lab=inn}
N 1510 -980 1510 -970 {lab=inn}
N 1590 -950 1590 -920 {lab=#net1}
N 1630 -970 1630 -880 {lab=vss}
N 1040 -920 1590 -920 {
lab=#net1}
N 1710 -1010 1830 -1010 {lab=out}
C {devices/vsource.sym} 930 -750 0 0 {name=VVcm value="DC CACE\{Vcm\} AC 1.0" savecurrent=false}
C {devices/lab_pin.sym} 790 -590 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 1260 -620 0 0 {name=Vvss value="DC CACE\{Vvss\}" savecurrent=false}
C {devices/lab_wire.sym} 1410 -1140 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} 1410 -880 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} 2100 -1010 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/res.sym} 1900 -980 0 0 {name=Rout
value=CACE\{Rout\}
device=resistor}
C {devices/capa.sym} 2040 -980 0 0 {name=Cout
value=CACE\{Cout\}}
C {devices/lab_pin.sym} 2080 -950 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 810 -620 0 0 {name=Vvdd value="DC CACE\{Vvdd\}" savecurrent=false}
C {devices/code_shown.sym} 40 -1300 0 0 {name=CONTROL only_toplevel=false value=".control
* Closed loop unity gain configuration
noise V(out) VVcm dec 10 CACE\{frequency\} CACE[CACE\{frequency\}*1e7]
* Everything having to do with noise is incredibly obscure. . .
setplot noise2
unset sqrnoise
let vn = onoise_total
echo $&vn > CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data
.endc
"}
C {devices/res.sym} 1110 -560 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 1110 -530 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} 930 -1030 0 1 {name=p2 sig_type=std_logic lab=inp}
C {devices/vcvs.sym} 1790 -750 0 1 {name=E1 value=1.0}
C {devices/lab_pin.sym} 1380 -800 0 1 {name=p3 sig_type=std_logic lab=inn}
C {OTA1336.sym} 1620 -1010 0 0 {name=x1}
C {devices/code_shown.sym} 30 -1590 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file CACE\{filename\}_CACE\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include CACE\{DUT_path\}

.lib cornerMOSlv.lib CACE\{corner\}
.lib cornerCAP.lib cap_typ

.option TEMP=CACE\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {isource.sym} 1040 -620 0 0 {name=Ibias value="DC CACE\{Ibias\}"}
C {title-3.sym} 0 0 0 0 {name=l2 author="IHP-GmbH 2026" title="CACE equivalent noise template" rev=1.0 lock=true}
