v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
T {Based on a template made by R. Timothy Edwards
November 27, 2023
Revision 0
Open sourced under Apache 2.0 license} 2030 -1670 0 0 0.4 0.4 {}
N 380 -400 520 -400 {
lab=VSUB}
N 1420 -820 1690 -820 {
lab=out}
N 1490 -760 1670 -760 {
lab=VSUB}
N 630 -730 1180 -730 {
lab=ena}
N 520 -860 1100 -860 {
lab=inp}
N 400 -950 400 -460 {
lab=vdd}
N 400 -950 1220 -950 {
lab=vdd}
N 850 -690 850 -460 {
lab=vss}
N 850 -690 1220 -690 {
lab=vss}
N 630 -730 630 -460 {
lab=ena}
N 520 -470 520 -400 {
lab=VSUB}
N 520 -860 520 -530 {
lab=inp}
N 1220 -950 1220 -860 {lab=vdd}
N 1100 -850 1130 -850 {lab=inp}
N 1100 -860 1100 -850 {lab=inp}
N 1100 -790 1130 -790 {lab=inm}
N 1100 -790 1100 -630 {lab=inm}
N 1180 -760 1180 -730 {lab=ena}
N 1220 -780 1220 -690 {lab=vss}
N 1300 -820 1420 -820 {lab=out}
N 1100 -850 1100 -840 {lab=inp}
N 1100 -800 1100 -790 {lab=inm}
N 1100 -630 1170 -630 {
lab=inm}
N 1230 -630 1420 -630 {lab=out}
N 1420 -820 1420 -630 {
lab=out}
N 1100 -570 1100 -400 {lab=VSUB}
N 520 -400 1100 -400 {
lab=VSUB}
C {devices/vsource.sym} 520 -500 0 0 {name=VVcm value="DC CACE\{Vcm\} AC CACE\{Vdiff\}" savecurrent=false}
C {devices/lab_pin.sym} 380 -400 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 850 -430 0 0 {name=Vvss value="DC CACE\{Vvss\}" savecurrent=false}
C {devices/lab_wire.sym} 1000 -950 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} 1000 -690 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} 1690 -820 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/res.sym} 1490 -790 0 0 {name=Rout
value=CACE\{Rout\}
device=resistor}
C {devices/capa.sym} 1630 -790 0 0 {name=Cout
value=CACE\{Cout\}}
C {devices/lab_pin.sym} 1670 -760 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/lab_pin.sym} 630 -700 0 1 {name=p29 sig_type=std_logic lab=ena}
C {devices/vsource.sym} 400 -430 0 0 {name=Vvdd value="DC CACE\{Vvdd\}" savecurrent=false}
C {devices/code_shown.sym} 30 -1330 0 0 {name=CONTROL only_toplevel=false value=".control
* AC parameters derivation
save all
ac dec 1001 1e1 1e9
let vog = db(V(out)/V(inp))
let vph = 180 * unwrap(phase(V(out)) - phase(V(inp)))/pi
let fbw = 0
let pm = 0
let gm = minimum(vog)
meas ac fbw WHEN vog=0 FALL=1
meas ac pm FIND vph WHEN vog=0 FALL=1
meas ac gm FIND vog WHEN vph=-180 FALL=1

let gainbw = $&fbw
let gmargin = -$&gm
let pmargin = 180 + $&pm
echo $&gainbw $&pmargin $&gmargin > CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data
quit
.endc
"}
C {devices/res.sym} 700 -370 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 700 -340 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} 1100 -840 2 1 {name=p2 sig_type=std_logic lab=inp}
C {devices/lab_pin.sym} 1100 -800 0 0 {name=p3 sig_type=std_logic lab=inm}
C {devices/code_shown.sym} 20 -1680 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file CACE\{filename\}_CACE\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include CACE\{DUT_path\}

.lib cornerMOSlv.lib CACE\{corner\}
.lib cornerCAP.lib cap_typ
.lib cornerRES.lib res_typ

.option TEMP=CACE\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {OTA1336.sym} 1210 -820 0 0 {name=x1}
C {isource.sym} 630 -430 0 0 {name=Ibias value="DC CACE\{Ibias\}"}
C {title-3.sym} 0 0 0 0 {name=l2 author="IHP-GmbH 2026" title="CACE Gain Bandwidth testbench" rev=1.0 lock=true}
C {ind.sym} 1200 -630 1 0 {name=L6
m=1
value=4G
footprint=1206
device=inductor}
C {capa.sym} 1100 -600 0 0 {name=C1
m=1
value=4G
footprint=1206
device="ceramic capacitor"}
