# Regenerate OTA1336 LibMan test fixture (.core + ota1336.projects).
# Requires: CommonDB build with xschem_to_core (build-tools/xschem_to_core.exe).
param(
    [string]$RepoUrl = "https://github.com/KrzysztofHerman/IHP__OTA1336.git",
    [string]$XschemToCore = "$PSScriptRoot\..\..\CommonDB\build-tools\xschem_to_core.exe"
)

$ErrorActionPreference = "Stop"
$DataRoot = (Resolve-Path "$PSScriptRoot\..\tests\data").Path
$CloneDir = Join-Path $DataRoot "_ota1336_clone"
$DestRoot = Join-Path $DataRoot "OTA1336"
$Roundtrip = Join-Path $DataRoot "_roundtrip.sch"

if (-not (Test-Path $XschemToCore)) {
    throw "xschem_to_core not found: $XschemToCore (build CommonDB target xschem_to_core first)"
}

if (Test-Path $CloneDir) { Remove-Item $CloneDir -Recurse -Force }
git clone --depth 1 $RepoUrl $CloneDir
$SrcRoot = Join-Path $CloneDir "OTA1336-main"
if (-not (Test-Path $SrcRoot)) { throw "Expected OTA1336-main/ in cloned repo" }

if (Test-Path $DestRoot) { Remove-Item $DestRoot -Recurse -Force }
Copy-Item $SrcRoot $DestRoot -Recurse
Remove-Item $CloneDir -Recurse -Force

Get-ChildItem $DestRoot -Recurse -Include *.sch, *.sym | ForEach-Object {
    if ($_.Name -eq "OTA1336.sch") { return }
    $stem = [IO.Path]::GetFileNameWithoutExtension($_.Name)
    $suffix = if ($_.Extension -eq ".sym") { "symbol" } else { "schematic" }
    $out = Join-Path $_.DirectoryName "$stem.$suffix.core"
    & $XschemToCore $_.FullName $out $Roundtrip | Out-Null
    if (-not (Test-Path $out)) { throw "Conversion failed: $($_.FullName)" }
}

$basicCore = Join-Path $DestRoot "schematic\xschem\OTA1336-basic.schematic.core"
$mainCore = Join-Path $DestRoot "schematic\xschem\OTA1336.schematic.core"
Copy-Item $basicCore $mainCore -Force

$lines = @(
    "# KLayout library definition file",
    "# Generated by LibMan (OTA1336 fixture)",
    ""
)
Get-ChildItem $DestRoot -Recurse -Filter *.core | Sort-Object FullName | ForEach-Object {
    $abs = $_.FullName.Replace("\", "/")
    $lines += "define(`"ihp_ota1336`", `"$abs`");"
}
[System.IO.File]::WriteAllLines((Join-Path $DataRoot "ota1336.projects"), $lines)
Remove-Item $Roundtrip -Force -ErrorAction SilentlyContinue

Write-Host "OTA1336 fixture ready: $DestRoot"
Write-Host "Project file: $(Join-Path $DataRoot 'ota1336.projects') ($($lines.Count - 3) defines)"
