#!/usr/bin/env bash
# Run from the qmake build directory after qmake (Windows/MinGW). Adds order-only stamp
# deps for Cap'n Proto consumers so parallel mingw32-make waits for Cap'n Proto first.
set -euo pipefail

MK="Makefile.Release"
if [[ ! -f "$MK" && -f Makefile.Debug ]]; then
    MK="Makefile.Debug"
fi
ORDER="capnp_object_order.mk"

if [[ ! -f "$MK" ]]; then
    echo "patch_capnp_makefile: $MK not found (run from build dir after qmake)" >&2
    exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STAMP_FILE="$ROOT/capnp-install/capnp_install_stamp"
BUILD_DIR="$(pwd)"

if command -v python3 >/dev/null 2>&1; then
    STAMP="$(python3 -c "import os.path; print(os.path.relpath(r'$STAMP_FILE', r'$BUILD_DIR').replace(os.sep, '/'))")"
elif command -v python >/dev/null 2>&1; then
    STAMP="$(python -c "import os.path; print(os.path.relpath(r'$STAMP_FILE', r'$BUILD_DIR').replace(os.sep, '/'))")"
else
    STAMP="../capnp-install/capnp_install_stamp"
fi

objects="$(
    awk '
        /^OBJECTS[[:space:]]*=/ {
            sub(/^OBJECTS[[:space:]]*=[[:space:]]*/, "")
            buf = $0
            while (buf ~ /\\[[:space:]]*$/) {
                sub(/\\[[:space:]]*$/, "", buf)
                if ((getline nextline) <= 0) break
                sub(/^[[:space:]]+/, "", nextline)
                buf = buf " " nextline
            }
            print buf
            exit
        }
    ' "$MK"
)"

if [[ -z "$objects" ]]; then
    echo "patch_capnp_makefile: no OBJECTS line in $MK" >&2
    exit 1
fi

needs_capnp() {
    case "$1" in
        *capnp*|*lstream*|*lstr*) return 0 ;;
        *) return 1 ;;
    esac
}

count=0
{
    echo "# Auto-generated by scripts/patch_capnp_makefile.sh — do not edit."
    echo "# STAMP=$STAMP"
    for o in $objects; do
        if needs_capnp "$o"; then
            echo "$o: | $STAMP"
            count=$((count + 1))
        fi
    done
} >"$ORDER"

if [[ "$count" -eq 0 ]]; then
    echo "patch_capnp_makefile: no Cap'n Proto object files matched in OBJECTS" >&2
    exit 1
fi

if ! grep -qF 'capnp_object_order.mk' "$MK"; then
    printf '\ninclude capnp_object_order.mk\n' >>"$MK"
fi

echo "patch_capnp_makefile: stamp=$STAMP, order-only deps for $count objects"
