#!/usr/bin/env bash
# Run from build/ after qmake (Windows/MinGW). Adds order-only stamp deps for Cap'n Proto
# consumers so parallel mingw32-make builds Cap'n Proto before compiling those .o files.
set -euo pipefail

STAMP="../capnp-install/capnp-built.stamp"
MK="Makefile.Release"
ORDER="capnp_object_order.mk"

if [[ ! -f "$MK" ]]; then
    echo "patch_capnp_makefile: $MK not found (run from build/ after qmake)" >&2
    exit 1
fi

objects="$(
    awk '
        /^OBJECTS[[:space:]]*=/ {
            sub(/^OBJECTS[[:space:]]*=[[:space:]]*/, "")
            buf = $0
            while (buf ~ /\\[[:space:]]*$/) {
                sub(/\\[[:space:]]*$/, "", buf)
                if ((getline nextline) <= 0) break
                sub(/^[[:space:]]+/, "", nextline)
                buf = buf " " nextline
            }
            print buf
            exit
        }
    ' "$MK"
)"

if [[ -z "$objects" ]]; then
    echo "patch_capnp_makefile: no OBJECTS line in $MK" >&2
    exit 1
fi

needs_capnp() {
    case "$1" in
        *capnp*|*lstream*|*lstr*) return 0 ;;
        *) return 1 ;;
    esac
}

count=0
{
    echo "# Auto-generated by scripts/patch_capnp_makefile.sh — do not edit."
    for o in $objects; do
        if needs_capnp "$o"; then
            # Order-only: build stamp before this object; stamp timestamp does not force rebuild.
            echo "$o: | $STAMP"
            count=$((count + 1))
        fi
    done
} >"$ORDER"

if [[ "$count" -eq 0 ]]; then
    echo "patch_capnp_makefile: no Cap'n Proto object files matched in OBJECTS" >&2
    exit 1
fi

if ! grep -qF 'capnp_object_order.mk' "$MK"; then
    printf '\ninclude capnp_object_order.mk\n' >>"$MK"
fi

echo "patch_capnp_makefile: added order-only stamp dep for $count Cap'n Proto objects"
