#!/usr/bin/env bash
# Run from build/ after qmake (Windows/MinGW). Merges stamp prerequisites into every
# release/*.o rule so parallel mingw32-make waits for Cap'n Proto before compiling.
set -euo pipefail

STAMP="../capnp-install/capnp-built.stamp"
MK="Makefile.Release"
ORDER="capnp_object_order.mk"

if [[ ! -f "$MK" ]]; then
    echo "patch_capnp_makefile: $MK not found (run from build/ after qmake)" >&2
    exit 1
fi

objects="$(
    awk '
        /^OBJECTS[[:space:]]*=/ {
            sub(/^OBJECTS[[:space:]]*=[[:space:]]*/, "")
            buf = $0
            while (buf ~ /\\[[:space:]]*$/) {
                sub(/\\[[:space:]]*$/, "", buf)
                if ((getline nextline) <= 0) break
                sub(/^[[:space:]]+/, "", nextline)
                buf = buf " " nextline
            }
            print buf
            exit
        }
    ' "$MK"
)"

if [[ -z "$objects" ]]; then
    echo "patch_capnp_makefile: no OBJECTS line in $MK" >&2
    exit 1
fi

{
    echo "# Auto-generated by scripts/patch_capnp_makefile.sh — do not edit."
    for o in $objects; do
        echo "$o: $STAMP"
    done
} >"$ORDER"

if ! grep -qF 'capnp_object_order.mk' "$MK"; then
    printf '\ninclude capnp_object_order.mk\n' >>"$MK"
fi

echo "patch_capnp_makefile: added stamp prerequisite for $(wc -w <<<"$objects" | tr -d ' ') objects"
