name: Build Qt LibMan (qmake)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Prepare build
      run: |
        mkdir build
        cd build
        qmake ../libman.pro

    - name: Build project
      run: |
        cd build
        make -j$(nproc)
